using BusinessLogic;
using CommonUtils;
using System.Collections.Generic;
using System.Data;
using System.Text;

namespace MuzeyServer
{
    public class ACLineSEAppService
    {
        public MuzeyResModel<ACLineSEResDto> GetDatas(MuzeyReqModel<ACLineSEReqDto> reqModel)
        {
            var lineName = new Dictionary<string,string>();
            lineName.Add("DA", "前围");
            lineName.Add("MC", "机舱");
            lineName.Add("FF", "前地板");
            lineName.Add("RC", "后地板");
            lineName.Add("RF", "顶盖");
            lineName.Add("HD", "前盖");
            lineName.Add("RDL", "左后门");
            lineName.Add("RDR", "右后门");
            lineName.Add("FDL", "左前门");
            lineName.Add("FDR", "右前门");
            lineName.Add("SIL", "左侧围内板");
            lineName.Add("SIR", "右侧围内板");
            lineName.Add("SOL", "左侧围外板");
            lineName.Add("SOR", "右侧围外板");
            lineName.Add("UB", "地板点定");
            lineName.Add("UR1", "地板补焊1线");
            lineName.Add("UR2", "地板补焊2线");
            lineName.Add("FI", "车身内总拼线");
            lineName.Add("RL2", "车身补焊2线");
            lineName.Add("FO", "车身外总拼线");
            lineName.Add("RL4", "车身补焊4线");
            lineName.Add("RL5", "车身补焊5线");
            lineName.Add("RL6", "车身补焊6线");
            lineName.Add("MF1", "装配线");
            lineName.Add("MF3", "表调线");

            var filter = reqModel.datas[0];

            var sqlStr = GetSql(filter.workShop + "※" + filter.workShop + "_AVI");
            if(filter.workShop == "AE")
            {
                sqlStr = sqlStr.Replace("BECarType", "AECarType");
                sqlStr = sqlStr.Replace("BodySelCode", "''");
                sqlStr = sqlStr.Replace("BodyUse", "''");
            }
            var strWhere = MuzeyReqUtil.GetSqlWhere(filter);
            sqlStr += strWhere;
            var totalCount = 0;
            var dt = SqlHelp.QueryPageList(sqlStr, "sTime Desc", reqModel.offset, reqModel.pageSize, out totalCount).Tables[0];

            var resModel = new MuzeyResModel<ACLineSEResDto>();            
            resModel.totalCount = totalCount;
            foreach(DataRow dr in dt.Rows)
            {
                var rd = new ACLineSEResDto();
                rd.vin = dr["vin"].ToStr();
                //rd.lineTypeName = dr["lineTypeName"].ToStr();
                if(filter.workShop == "AE")
                {
                    rd.lineName = dr["lineName"].ToStr();
                }
                else
                {
                    foreach(var kv in lineName)
                    {
                        if (dr["line"].ToStr().Contains(kv.Key))
                        {
                            rd.lineName = kv.Value;
                            break;
                        }
                    }
                }
                rd.sTime = dr["sTime"].ToStr();
                rd.eTime = dr["eTime"].ToStr();
                rd.orderNum = dr["orderNum"].ToStr();
                rd.orderType = dr["orderType"].ToStr();
                rd.carType = dr["carType"].ToStr();
                rd.wsCarType = dr["wsCarType"].ToStr();
                rd.bodySelCode = dr["bodySelCode"].ToStr();
                rd.bodyUse = dr["bodyUse"].ToStr();
                rd.serialNumber = dr["serialNumber"].ToStr();
                rd.line = dr["line"].ToStr();
                resModel.datas.Add(rd);
            }
            return resModel;
        }

        private string GetSql(string dbName)
        {
            var strBuffer = new StringBuilder();
            strBuffer.AppendLine(string.Format("◎{0}◎", dbName));
            strBuffer.AppendLine(" select * from(");
            strBuffer.AppendLine(" select ");
            strBuffer.AppendLine(" t1.vin ");
            strBuffer.AppendLine(" ,t1.lineName ");
            strBuffer.AppendLine(" ,t1.ReportName as sReportName ");
            strBuffer.AppendLine(" ,t2.ReportName as eReportName ");
            strBuffer.AppendLine(" ,t1.sTime ");
            strBuffer.AppendLine(" ,t2.eTime ");
            strBuffer.AppendLine(" ,t1.LineType ");
            strBuffer.AppendLine(" ,t1.orderNum ");
            strBuffer.AppendLine(" ,t1.orderType ");
            strBuffer.AppendLine(" ,t1.carType ");
            strBuffer.AppendLine(" ,t1.wsCarType ");
            strBuffer.AppendLine(" ,t1.bodySelCode ");
            strBuffer.AppendLine(" ,t1.bodyUse ");
            strBuffer.AppendLine(" ,t1.serialNumber ");
            strBuffer.AppendLine(" ,t1.line ");
            strBuffer.AppendLine(" from ");
            strBuffer.AppendLine(" ( ");
            strBuffer.AppendLine(" select ");
            strBuffer.AppendLine(" vin ");
            strBuffer.AppendLine(" ,'PBS上线' as ReportName ");
            strBuffer.AppendLine(" ,ReportTime as sTime ");
            strBuffer.AppendLine(" , LineType ");
            strBuffer.AppendLine(" ,'PBS' as lineName ");
            strBuffer.AppendLine(" ,OrderNum as orderNum ");
            strBuffer.AppendLine(" ,OrderType as orderType ");
            strBuffer.AppendLine(" ,CarType as carType ");
            strBuffer.AppendLine(" ,BECarType as wsCarType ");
            strBuffer.AppendLine(" ,BodySelCode as bodySelCode ");
            strBuffer.AppendLine(" ,BodyUse as bodyUse ");
            strBuffer.AppendLine(" ,SerialNumber as serialNumber ");
            strBuffer.AppendLine(" ,Line as line ");
            strBuffer.AppendLine(" from AVI_REPORT_MQ where ReportID = 'PBS002') t1 ");
            strBuffer.AppendLine(" Left JOIN ");
            strBuffer.AppendLine(" (select vin,'PBS下线' as ReportName,ReportTime as eTime from AVI_REPORT_MQ where ReportID = 'PBS003') t2 ");
            strBuffer.AppendLine(" ON ");
            strBuffer.AppendLine(" t1.vin=t2.vin ");
            strBuffer.AppendLine(" UNION ALL ");
            strBuffer.AppendLine(" select ");
            strBuffer.AppendLine(" t1.vin ");
            strBuffer.AppendLine(" ,t1.lineName ");
            strBuffer.AppendLine(" ,t1.ReportName as sReportName ");
            strBuffer.AppendLine(" ,t2.ReportName as eReportName ");
            strBuffer.AppendLine(" ,t1.sTime ");
            strBuffer.AppendLine(" ,t2.eTime ");
            strBuffer.AppendLine(" ,t1.LineType ");
            strBuffer.AppendLine(" ,t1.orderNum ");
            strBuffer.AppendLine(" ,t1.orderType ");
            strBuffer.AppendLine(" ,t1.carType ");
            strBuffer.AppendLine(" ,t1.wsCarType ");
            strBuffer.AppendLine(" ,t1.bodySelCode ");
            strBuffer.AppendLine(" ,t1.bodyUse ");
            strBuffer.AppendLine(" ,t1.serialNumber ");
            strBuffer.AppendLine(" ,t1.line ");
            strBuffer.AppendLine(" from ");
            strBuffer.AppendLine(" ( ");
            strBuffer.AppendLine(" select ");
            strBuffer.AppendLine(" vin ");
            strBuffer.AppendLine(" ,'预内饰线上线' as ReportName ");
            strBuffer.AppendLine(" ,ReportTime as sTime ");
            strBuffer.AppendLine(" , LineType ");
            strBuffer.AppendLine(" ,'预内饰线' as lineName ");
            strBuffer.AppendLine(" ,OrderNum as orderNum ");
            strBuffer.AppendLine(" ,OrderType as orderType ");
            strBuffer.AppendLine(" ,CarType as carType ");
            strBuffer.AppendLine(" ,BECarType as wsCarType ");
            strBuffer.AppendLine(" ,BodySelCode as bodySelCode ");
            strBuffer.AppendLine(" ,BodyUse as bodyUse ");
            strBuffer.AppendLine(" ,SerialNumber as serialNumber ");
            strBuffer.AppendLine(" ,Line as line ");
            strBuffer.AppendLine(" from AVI_REPORT_MQ where ReportID = 'P01') t1 ");
            strBuffer.AppendLine(" Left JOIN ");
            strBuffer.AppendLine(" (select vin,'预内饰线下线' as ReportName,ReportTime as eTime from AVI_REPORT_MQ where ReportID = 'P09') t2 ");
            strBuffer.AppendLine(" ON ");
            strBuffer.AppendLine(" t1.vin=t2.vin ");
            strBuffer.AppendLine(" UNION ALL ");
            strBuffer.AppendLine(" select ");
            strBuffer.AppendLine(" t1.vin ");
            strBuffer.AppendLine(" ,t1.lineName ");
            strBuffer.AppendLine(" ,t1.ReportName as sReportName ");
            strBuffer.AppendLine(" ,t2.ReportName as eReportName ");
            strBuffer.AppendLine(" ,t1.sTime ");
            strBuffer.AppendLine(" ,t2.eTime ");
            strBuffer.AppendLine(" ,t1.LineType ");
            strBuffer.AppendLine(" ,t1.orderNum ");
            strBuffer.AppendLine(" ,t1.orderType ");
            strBuffer.AppendLine(" ,t1.carType ");
            strBuffer.AppendLine(" ,t1.wsCarType ");
            strBuffer.AppendLine(" ,t1.bodySelCode ");
            strBuffer.AppendLine(" ,t1.bodyUse ");
            strBuffer.AppendLine(" ,t1.serialNumber ");
            strBuffer.AppendLine(" ,t1.line ");
            strBuffer.AppendLine(" from ");
            strBuffer.AppendLine(" ( ");
            strBuffer.AppendLine(" select ");
            strBuffer.AppendLine(" vin ");
            strBuffer.AppendLine(" ,'内饰一线上线' as ReportName ");
            strBuffer.AppendLine(" ,ReportTime as sTime ");
            strBuffer.AppendLine(" , LineType ");
            strBuffer.AppendLine(" ,'内饰一线' as lineName ");
            strBuffer.AppendLine(" ,OrderNum as orderNum ");
            strBuffer.AppendLine(" ,OrderType as orderType ");
            strBuffer.AppendLine(" ,CarType as carType ");
            strBuffer.AppendLine(" ,BECarType as wsCarType ");
            strBuffer.AppendLine(" ,BodySelCode as bodySelCode ");
            strBuffer.AppendLine(" ,BodyUse as bodyUse ");
            strBuffer.AppendLine(" ,SerialNumber as serialNumber ");
            strBuffer.AppendLine(" ,Line as line ");
            strBuffer.AppendLine(" from AVI_REPORT_MQ where ReportID = 'PBS004') t1 ");
            strBuffer.AppendLine(" Left JOIN ");
            strBuffer.AppendLine(" (select vin,'内饰一线下线' as ReportName,ReportTime as eTime from AVI_REPORT_MQ where ReportID = '026') t2 ");
            strBuffer.AppendLine(" ON ");
            strBuffer.AppendLine(" t1.vin=t2.vin ");
            strBuffer.AppendLine(" UNION ALL ");
            strBuffer.AppendLine(" select ");
            strBuffer.AppendLine(" t1.vin ");
            strBuffer.AppendLine(" ,t1.lineName ");
            strBuffer.AppendLine(" ,t1.ReportName as sReportName ");
            strBuffer.AppendLine(" ,t2.ReportName as eReportName ");
            strBuffer.AppendLine(" ,t1.sTime ");
            strBuffer.AppendLine(" ,t2.eTime ");
            strBuffer.AppendLine(" ,t1.LineType ");
            strBuffer.AppendLine(" ,t1.orderNum ");
            strBuffer.AppendLine(" ,t1.orderType ");
            strBuffer.AppendLine(" ,t1.carType ");
            strBuffer.AppendLine(" ,t1.wsCarType ");
            strBuffer.AppendLine(" ,t1.bodySelCode ");
            strBuffer.AppendLine(" ,t1.bodyUse ");
            strBuffer.AppendLine(" ,t1.serialNumber ");
            strBuffer.AppendLine(" ,t1.line ");
            strBuffer.AppendLine(" from ");
            strBuffer.AppendLine(" ( ");
            strBuffer.AppendLine(" select ");
            strBuffer.AppendLine(" vin ");
            strBuffer.AppendLine(" ,'内饰二线上线' as ReportName ");
            strBuffer.AppendLine(" ,ReportTime as sTime ");
            strBuffer.AppendLine(" , LineType ");
            strBuffer.AppendLine(" ,'内饰二线' as lineName ");
            strBuffer.AppendLine(" ,OrderNum as orderNum ");
            strBuffer.AppendLine(" ,OrderType as orderType ");
            strBuffer.AppendLine(" ,CarType as carType ");
            strBuffer.AppendLine(" ,BECarType as wsCarType ");
            strBuffer.AppendLine(" ,BodySelCode as bodySelCode ");
            strBuffer.AppendLine(" ,BodyUse as bodyUse ");
            strBuffer.AppendLine(" ,SerialNumber as serialNumber ");
            strBuffer.AppendLine(" ,Line as line ");
            strBuffer.AppendLine(" from AVI_REPORT_MQ where ReportID = '027') t1 ");
            strBuffer.AppendLine(" Left JOIN ");
            strBuffer.AppendLine(" (select vin,'内饰二线下线' as ReportName,ReportTime as eTime from AVI_REPORT_MQ where ReportID = '052') t2 ");
            strBuffer.AppendLine(" ON ");
            strBuffer.AppendLine(" t1.vin=t2.vin ");
            strBuffer.AppendLine(" UNION ALL ");
            strBuffer.AppendLine(" select ");
            strBuffer.AppendLine(" t1.vin ");
            strBuffer.AppendLine(" ,t1.lineName ");
            strBuffer.AppendLine(" ,t1.ReportName as sReportName ");
            strBuffer.AppendLine(" ,t2.ReportName as eReportName ");
            strBuffer.AppendLine(" ,t1.sTime ");
            strBuffer.AppendLine(" ,t2.eTime ");
            strBuffer.AppendLine(" ,t1.LineType ");
            strBuffer.AppendLine(" ,t1.orderNum ");
            strBuffer.AppendLine(" ,t1.orderType ");
            strBuffer.AppendLine(" ,t1.carType ");
            strBuffer.AppendLine(" ,t1.wsCarType ");
            strBuffer.AppendLine(" ,t1.bodySelCode ");
            strBuffer.AppendLine(" ,t1.bodyUse ");
            strBuffer.AppendLine(" ,t1.serialNumber ");
            strBuffer.AppendLine(" ,t1.line ");
            strBuffer.AppendLine(" from ");
            strBuffer.AppendLine(" ( ");
            strBuffer.AppendLine(" select ");
            strBuffer.AppendLine(" vin ");
            strBuffer.AppendLine(" ,'底盘一线上线' as ReportName ");
            strBuffer.AppendLine(" ,ReportTime as sTime ");
            strBuffer.AppendLine(" , LineType ");
            strBuffer.AppendLine(" ,'底盘一线' as lineName ");
            strBuffer.AppendLine(" ,OrderNum as orderNum ");
            strBuffer.AppendLine(" ,OrderType as orderType ");
            strBuffer.AppendLine(" ,CarType as carType ");
            strBuffer.AppendLine(" ,BECarType as wsCarType ");
            strBuffer.AppendLine(" ,BodySelCode as bodySelCode ");
            strBuffer.AppendLine(" ,BodyUse as bodyUse ");
            strBuffer.AppendLine(" ,SerialNumber as serialNumber ");
            strBuffer.AppendLine(" ,Line as line ");
            strBuffer.AppendLine(" from AVI_REPORT_MQ where ReportID = '102') t1 ");
            strBuffer.AppendLine(" Left JOIN ");
            strBuffer.AppendLine(" (select vin,'底盘一线下线' as ReportName,ReportTime as eTime from AVI_REPORT_MQ where ReportID = '114') t2 ");
            strBuffer.AppendLine(" ON ");
            strBuffer.AppendLine(" t1.vin=t2.vin ");
            strBuffer.AppendLine(" UNION ALL ");
            strBuffer.AppendLine(" select ");
            strBuffer.AppendLine(" t1.vin ");
            strBuffer.AppendLine(" ,t1.lineName ");
            strBuffer.AppendLine(" ,t1.ReportName as sReportName ");
            strBuffer.AppendLine(" ,t2.ReportName as eReportName ");
            strBuffer.AppendLine(" ,t1.sTime ");
            strBuffer.AppendLine(" ,t2.eTime ");
            strBuffer.AppendLine(" ,t1.LineType ");
            strBuffer.AppendLine(" ,t1.orderNum ");
            strBuffer.AppendLine(" ,t1.orderType ");
            strBuffer.AppendLine(" ,t1.carType ");
            strBuffer.AppendLine(" ,t1.wsCarType ");
            strBuffer.AppendLine(" ,t1.bodySelCode ");
            strBuffer.AppendLine(" ,t1.bodyUse ");
            strBuffer.AppendLine(" ,t1.serialNumber ");
            strBuffer.AppendLine(" ,t1.line ");
            strBuffer.AppendLine(" from ");
            strBuffer.AppendLine(" ( ");
            strBuffer.AppendLine(" select ");
            strBuffer.AppendLine(" vin ");
            strBuffer.AppendLine(" ,'底盘二线上线' as ReportName ");
            strBuffer.AppendLine(" ,ReportTime as sTime ");
            strBuffer.AppendLine(" , LineType ");
            strBuffer.AppendLine(" ,'底盘二线' as lineName ");
            strBuffer.AppendLine(" ,OrderNum as orderNum ");
            strBuffer.AppendLine(" ,OrderType as orderType ");
            strBuffer.AppendLine(" ,CarType as carType ");
            strBuffer.AppendLine(" ,BECarType as wsCarType ");
            strBuffer.AppendLine(" ,BodySelCode as bodySelCode ");
            strBuffer.AppendLine(" ,BodyUse as bodyUse ");
            strBuffer.AppendLine(" ,SerialNumber as serialNumber ");
            strBuffer.AppendLine(" ,Line as line ");
            strBuffer.AppendLine(" from AVI_REPORT_MQ where ReportID = '116') t1 ");
            strBuffer.AppendLine(" Left JOIN ");
            strBuffer.AppendLine(" (select vin,'底盘二线下线' as ReportName,ReportTime as eTime from AVI_REPORT_MQ where ReportID = '130') t2 ");
            strBuffer.AppendLine(" ON ");
            strBuffer.AppendLine(" t1.vin=t2.vin ");
            strBuffer.AppendLine(" UNION ALL ");
            strBuffer.AppendLine(" select ");
            strBuffer.AppendLine(" t1.vin ");
            strBuffer.AppendLine(" ,t1.lineName ");
            strBuffer.AppendLine(" ,t1.ReportName as sReportName ");
            strBuffer.AppendLine(" ,t2.ReportName as eReportName ");
            strBuffer.AppendLine(" ,t1.sTime ");
            strBuffer.AppendLine(" ,t2.eTime ");
            strBuffer.AppendLine(" ,t1.LineType ");
            strBuffer.AppendLine(" ,t1.orderNum ");
            strBuffer.AppendLine(" ,t1.orderType ");
            strBuffer.AppendLine(" ,t1.carType ");
            strBuffer.AppendLine(" ,t1.wsCarType ");
            strBuffer.AppendLine(" ,t1.bodySelCode ");
            strBuffer.AppendLine(" ,t1.bodyUse ");
            strBuffer.AppendLine(" ,t1.serialNumber ");
            strBuffer.AppendLine(" ,t1.line ");
            strBuffer.AppendLine(" from ");
            strBuffer.AppendLine(" ( ");
            strBuffer.AppendLine(" select ");
            strBuffer.AppendLine(" vin ");
            strBuffer.AppendLine(" ,'终装一线上线' as ReportName ");
            strBuffer.AppendLine(" ,ReportTime as sTime ");
            strBuffer.AppendLine(" , LineType ");
            strBuffer.AppendLine(" ,'终装一线' as lineName ");
            strBuffer.AppendLine(" ,OrderNum as orderNum ");
            strBuffer.AppendLine(" ,OrderType as orderType ");
            strBuffer.AppendLine(" ,CarType as carType ");
            strBuffer.AppendLine(" ,BECarType as wsCarType ");
            strBuffer.AppendLine(" ,BodySelCode as bodySelCode ");
            strBuffer.AppendLine(" ,BodyUse as bodyUse ");
            strBuffer.AppendLine(" ,SerialNumber as serialNumber ");
            strBuffer.AppendLine(" ,Line as line ");
            strBuffer.AppendLine(" from AVI_REPORT_MQ where ReportID = '201') t1 ");
            strBuffer.AppendLine(" Left JOIN ");
            strBuffer.AppendLine(" (select vin,'终装一线下线' as ReportName,ReportTime as eTime from AVI_REPORT_MQ where ReportID = '224') t2 ");
            strBuffer.AppendLine(" ON ");
            strBuffer.AppendLine(" t1.vin=t2.vin ");
            strBuffer.AppendLine(" UNION ALL ");
            strBuffer.AppendLine(" select ");
            strBuffer.AppendLine(" t1.vin ");
            strBuffer.AppendLine(" ,t1.lineName ");
            strBuffer.AppendLine(" ,t1.ReportName as sReportName ");
            strBuffer.AppendLine(" ,t2.ReportName as eReportName ");
            strBuffer.AppendLine(" ,t1.sTime ");
            strBuffer.AppendLine(" ,t2.eTime ");
            strBuffer.AppendLine(" ,t1.LineType ");
            strBuffer.AppendLine(" ,t1.orderNum ");
            strBuffer.AppendLine(" ,t1.orderType ");
            strBuffer.AppendLine(" ,t1.carType ");
            strBuffer.AppendLine(" ,t1.wsCarType ");
            strBuffer.AppendLine(" ,t1.bodySelCode ");
            strBuffer.AppendLine(" ,t1.bodyUse ");
            strBuffer.AppendLine(" ,t1.serialNumber ");
            strBuffer.AppendLine(" ,t1.line ");
            strBuffer.AppendLine(" from ");
            strBuffer.AppendLine(" ( ");
            strBuffer.AppendLine(" select ");
            strBuffer.AppendLine(" vin ");
            strBuffer.AppendLine(" ,'终装二线上线' as ReportName ");
            strBuffer.AppendLine(" ,ReportTime as sTime ");
            strBuffer.AppendLine(" , LineType ");
            strBuffer.AppendLine(" ,'终装二线' as lineName ");
            strBuffer.AppendLine(" ,OrderNum as orderNum ");
            strBuffer.AppendLine(" ,OrderType as orderType ");
            strBuffer.AppendLine(" ,CarType as carType ");
            strBuffer.AppendLine(" ,BECarType as wsCarType ");
            strBuffer.AppendLine(" ,BodySelCode as bodySelCode ");
            strBuffer.AppendLine(" ,BodyUse as bodyUse ");
            strBuffer.AppendLine(" ,SerialNumber as serialNumber ");
            strBuffer.AppendLine(" ,Line as line ");
            strBuffer.AppendLine(" from AVI_REPORT_MQ where ReportID = '225') t1 ");
            strBuffer.AppendLine(" Left JOIN ");
            strBuffer.AppendLine(" (select vin,'终装二线下线' as ReportName,ReportTime as eTime from AVI_REPORT_MQ where ReportID = '248') t2 ");
            strBuffer.AppendLine(" ON ");
            strBuffer.AppendLine(" t1.vin=t2.vin ");
            strBuffer.AppendLine(" UNION ALL ");
            strBuffer.AppendLine(" select ");
            strBuffer.AppendLine(" t1.vin ");
            strBuffer.AppendLine(" ,t1.lineName ");
            strBuffer.AppendLine(" ,t1.ReportName as sReportName ");
            strBuffer.AppendLine(" ,t2.ReportName as eReportName ");
            strBuffer.AppendLine(" ,t1.sTime ");
            strBuffer.AppendLine(" ,t2.eTime ");
            strBuffer.AppendLine(" ,t1.LineType ");
            strBuffer.AppendLine(" ,t1.orderNum ");
            strBuffer.AppendLine(" ,t1.orderType ");
            strBuffer.AppendLine(" ,t1.carType ");
            strBuffer.AppendLine(" ,t1.wsCarType ");
            strBuffer.AppendLine(" ,t1.bodySelCode ");
            strBuffer.AppendLine(" ,t1.bodyUse ");
            strBuffer.AppendLine(" ,t1.serialNumber ");
            strBuffer.AppendLine(" ,t1.line ");
            strBuffer.AppendLine(" from ");
            strBuffer.AppendLine(" ( ");
            strBuffer.AppendLine(" select ");
            strBuffer.AppendLine(" vin ");
            strBuffer.AppendLine(" ,'报交线上线' as ReportName ");
            strBuffer.AppendLine(" ,ReportTime as sTime ");
            strBuffer.AppendLine(" , LineType ");
            strBuffer.AppendLine(" ,'报交线' as lineName ");
            strBuffer.AppendLine(" ,OrderNum as orderNum ");
            strBuffer.AppendLine(" ,OrderType as orderType ");
            strBuffer.AppendLine(" ,CarType as carType ");
            strBuffer.AppendLine(" ,BECarType as wsCarType ");
            strBuffer.AppendLine(" ,BodySelCode as bodySelCode ");
            strBuffer.AppendLine(" ,BodyUse as bodyUse ");
            strBuffer.AppendLine(" ,SerialNumber as serialNumber ");
            strBuffer.AppendLine(" ,Line as line ");
            strBuffer.AppendLine(" from AVI_REPORT_MQ where ReportID = '501') t1 ");
            strBuffer.AppendLine(" Left JOIN ");
            strBuffer.AppendLine(" (select vin,'报交线下线' as ReportName,ReportTime as eTime from AVI_REPORT_MQ where ReportID = '503') t2 ");
            strBuffer.AppendLine(" ON ");
            strBuffer.AppendLine(" t1.vin=t2.vin ");
            strBuffer.AppendLine(" UNION ALL ");
            strBuffer.AppendLine(" select ");
            strBuffer.AppendLine(" t1.vin ");
            strBuffer.AppendLine(" ,t1.lineName ");
            strBuffer.AppendLine(" ,t1.ReportName as sReportName ");
            strBuffer.AppendLine(" ,t2.ReportName as eReportName ");
            strBuffer.AppendLine(" ,t1.sTime ");
            strBuffer.AppendLine(" ,t2.eTime ");
            strBuffer.AppendLine(" ,t1.LineType ");
            strBuffer.AppendLine(" ,t1.orderNum ");
            strBuffer.AppendLine(" ,t1.orderType ");
            strBuffer.AppendLine(" ,t1.carType ");
            strBuffer.AppendLine(" ,t1.wsCarType ");
            strBuffer.AppendLine(" ,t1.bodySelCode ");
            strBuffer.AppendLine(" ,t1.bodyUse ");
            strBuffer.AppendLine(" ,t1.serialNumber ");
            strBuffer.AppendLine(" ,t1.line ");
            strBuffer.AppendLine(" from ");
            strBuffer.AppendLine(" ( ");
            strBuffer.AppendLine(" select ");
            strBuffer.AppendLine(" vin ");
            strBuffer.AppendLine(" ,'AGV动力总成分装线上线' as ReportName ");
            strBuffer.AppendLine(" ,ReportTime as sTime ");
            strBuffer.AppendLine(" , LineType ");
            strBuffer.AppendLine(" ,'AGV动力总成分装线' as lineName ");
            strBuffer.AppendLine(" ,OrderNum as orderNum ");
            strBuffer.AppendLine(" ,OrderType as orderType ");
            strBuffer.AppendLine(" ,CarType as carType ");
            strBuffer.AppendLine(" ,BECarType as wsCarType ");
            strBuffer.AppendLine(" ,BodySelCode as bodySelCode ");
            strBuffer.AppendLine(" ,BodyUse as bodyUse ");
            strBuffer.AppendLine(" ,SerialNumber as serialNumber ");
            strBuffer.AppendLine(" ,Line as line ");
            strBuffer.AppendLine(" from AVI_REPORT_MQ where ReportID = '601') t1 ");
            strBuffer.AppendLine(" Left JOIN ");
            strBuffer.AppendLine(" (select vin,'AGV动力总成分装线下线' as ReportName,ReportTime as eTime from AVI_REPORT_MQ where ReportID = '605') t2 ");
            strBuffer.AppendLine(" ON ");
            strBuffer.AppendLine(" t1.vin=t2.vin ");
            strBuffer.AppendLine(" UNION ALL ");
            strBuffer.AppendLine(" select ");
            strBuffer.AppendLine(" t1.vin ");
            strBuffer.AppendLine(" ,t1.lineName ");
            strBuffer.AppendLine(" ,t1.ReportName as sReportName ");
            strBuffer.AppendLine(" ,t2.ReportName as eReportName ");
            strBuffer.AppendLine(" ,t1.sTime ");
            strBuffer.AppendLine(" ,t2.eTime ");
            strBuffer.AppendLine(" ,t1.LineType ");
            strBuffer.AppendLine(" ,t1.orderNum ");
            strBuffer.AppendLine(" ,t1.orderType ");
            strBuffer.AppendLine(" ,t1.carType ");
            strBuffer.AppendLine(" ,t1.wsCarType ");
            strBuffer.AppendLine(" ,t1.bodySelCode ");
            strBuffer.AppendLine(" ,t1.bodyUse ");
            strBuffer.AppendLine(" ,t1.serialNumber ");
            strBuffer.AppendLine(" ,t1.line ");
            strBuffer.AppendLine(" from ");
            strBuffer.AppendLine(" ( ");
            strBuffer.AppendLine(" select ");
            strBuffer.AppendLine(" vin ");
            strBuffer.AppendLine(" ,'左侧车门装配线上线' as ReportName ");
            strBuffer.AppendLine(" ,ReportTime as sTime ");
            strBuffer.AppendLine(" , LineType ");
            strBuffer.AppendLine(" ,'左侧车门装配线' as lineName ");
            strBuffer.AppendLine(" ,OrderNum as orderNum ");
            strBuffer.AppendLine(" ,OrderType as orderType ");
            strBuffer.AppendLine(" ,CarType as carType ");
            strBuffer.AppendLine(" ,BECarType as wsCarType ");
            strBuffer.AppendLine(" ,BodySelCode as bodySelCode ");
            strBuffer.AppendLine(" ,BodyUse as bodyUse ");
            strBuffer.AppendLine(" ,SerialNumber as serialNumber ");
            strBuffer.AppendLine(" ,Line as line ");
            strBuffer.AppendLine(" from AVI_REPORT_MQ where ReportID = '701L') t1 ");
            strBuffer.AppendLine(" Left JOIN ");
            strBuffer.AppendLine(" (select vin,'左侧车门装配线下线' as ReportName,ReportTime as eTime from AVI_REPORT_MQ where ReportID = '720L') t2 ");
            strBuffer.AppendLine(" ON ");
            strBuffer.AppendLine(" t1.vin=t2.vin ");
            strBuffer.AppendLine(" UNION ALL ");
            strBuffer.AppendLine(" select ");
            strBuffer.AppendLine(" t1.vin ");
            strBuffer.AppendLine(" ,t1.lineName ");
            strBuffer.AppendLine(" ,t1.ReportName as sReportName ");
            strBuffer.AppendLine(" ,t2.ReportName as eReportName ");
            strBuffer.AppendLine(" ,t1.sTime ");
            strBuffer.AppendLine(" ,t2.eTime ");
            strBuffer.AppendLine(" ,t1.LineType ");
            strBuffer.AppendLine(" ,t1.orderNum ");
            strBuffer.AppendLine(" ,t1.orderType ");
            strBuffer.AppendLine(" ,t1.carType ");
            strBuffer.AppendLine(" ,t1.wsCarType ");
            strBuffer.AppendLine(" ,t1.bodySelCode ");
            strBuffer.AppendLine(" ,t1.bodyUse ");
            strBuffer.AppendLine(" ,t1.serialNumber ");
            strBuffer.AppendLine(" ,t1.line ");
            strBuffer.AppendLine(" from ");
            strBuffer.AppendLine(" ( ");
            strBuffer.AppendLine(" select ");
            strBuffer.AppendLine(" vin ");
            strBuffer.AppendLine(" ,'右侧车门装配线上线' as ReportName ");
            strBuffer.AppendLine(" ,ReportTime as sTime ");
            strBuffer.AppendLine(" , LineType ");
            strBuffer.AppendLine(" ,'右侧车门装配线' as lineName ");
            strBuffer.AppendLine(" ,OrderNum as orderNum ");
            strBuffer.AppendLine(" ,OrderType as orderType ");
            strBuffer.AppendLine(" ,CarType as carType ");
            strBuffer.AppendLine(" ,BECarType as wsCarType ");
            strBuffer.AppendLine(" ,BodySelCode as bodySelCode ");
            strBuffer.AppendLine(" ,BodyUse as bodyUse ");
            strBuffer.AppendLine(" ,SerialNumber as serialNumber ");
            strBuffer.AppendLine(" ,Line as line ");
            strBuffer.AppendLine(" from AVI_REPORT_MQ where ReportID = '701R') t1 ");
            strBuffer.AppendLine(" Left JOIN ");
            strBuffer.AppendLine(" (select vin,'右侧车门装配线下线' as ReportName,ReportTime as eTime from AVI_REPORT_MQ where ReportID = '720R') t2 ");
            strBuffer.AppendLine(" ON ");
            strBuffer.AppendLine(" t1.vin=t2.vin ");
            strBuffer.AppendLine(" UNION ALL ");
            strBuffer.AppendLine(" select ");
            strBuffer.AppendLine(" t1.vin ");
            strBuffer.AppendLine(" ,t1.lineName ");
            strBuffer.AppendLine(" ,t1.ReportName as sReportName ");
            strBuffer.AppendLine(" ,t2.ReportName as eReportName ");
            strBuffer.AppendLine(" ,t1.sTime ");
            strBuffer.AppendLine(" ,t2.eTime ");
            strBuffer.AppendLine(" ,t1.LineType ");
            strBuffer.AppendLine(" ,t1.orderNum ");
            strBuffer.AppendLine(" ,t1.orderType ");
            strBuffer.AppendLine(" ,t1.carType ");
            strBuffer.AppendLine(" ,t1.wsCarType ");
            strBuffer.AppendLine(" ,t1.bodySelCode ");
            strBuffer.AppendLine(" ,t1.bodyUse ");
            strBuffer.AppendLine(" ,t1.serialNumber ");
            strBuffer.AppendLine(" ,t1.line ");
            strBuffer.AppendLine(" from ");
            strBuffer.AppendLine(" ( ");
            strBuffer.AppendLine(" select ");
            strBuffer.AppendLine(" vin ");
            strBuffer.AppendLine(" ,'前围DA上线' as ReportName ");
            strBuffer.AppendLine(" ,ReportTime as sTime ");
            strBuffer.AppendLine(" , LineType ");
            strBuffer.AppendLine(" ,'前围DA' as lineName ");
            strBuffer.AppendLine(" ,OrderNum as orderNum ");
            strBuffer.AppendLine(" ,OrderType as orderType ");
            strBuffer.AppendLine(" ,CarType as carType ");
            strBuffer.AppendLine(" ,BECarType as wsCarType ");
            strBuffer.AppendLine(" ,BodySelCode as bodySelCode ");
            strBuffer.AppendLine(" ,BodyUse as bodyUse ");
            strBuffer.AppendLine(" ,SerialNumber as serialNumber ");
            strBuffer.AppendLine(" ,Line as line ");
            strBuffer.AppendLine(" from AVI_REPORT_MQ where ReportID = 'DA1000') t1 ");
            strBuffer.AppendLine(" Left JOIN ");
            strBuffer.AppendLine(" (select vin,'前围DA下线' as ReportName,ReportTime as eTime from AVI_REPORT_MQ where ReportID = 'DA1080') t2 ");
            strBuffer.AppendLine(" ON ");
            strBuffer.AppendLine(" t1.vin=t2.vin ");
            strBuffer.AppendLine(" UNION ALL ");
            strBuffer.AppendLine(" select ");
            strBuffer.AppendLine(" t1.vin ");
            strBuffer.AppendLine(" ,t1.lineName ");
            strBuffer.AppendLine(" ,t1.ReportName as sReportName ");
            strBuffer.AppendLine(" ,t2.ReportName as eReportName ");
            strBuffer.AppendLine(" ,t1.sTime ");
            strBuffer.AppendLine(" ,t2.eTime ");
            strBuffer.AppendLine(" ,t1.LineType ");
            strBuffer.AppendLine(" ,t1.orderNum ");
            strBuffer.AppendLine(" ,t1.orderType ");
            strBuffer.AppendLine(" ,t1.carType ");
            strBuffer.AppendLine(" ,t1.wsCarType ");
            strBuffer.AppendLine(" ,t1.bodySelCode ");
            strBuffer.AppendLine(" ,t1.bodyUse ");
            strBuffer.AppendLine(" ,t1.serialNumber ");
            strBuffer.AppendLine(" ,t1.line ");
            strBuffer.AppendLine(" from ");
            strBuffer.AppendLine(" ( ");
            strBuffer.AppendLine(" select ");
            strBuffer.AppendLine(" vin ");
            strBuffer.AppendLine(" ,'机舱MC上线' as ReportName ");
            strBuffer.AppendLine(" ,ReportTime as sTime ");
            strBuffer.AppendLine(" , LineType ");
            strBuffer.AppendLine(" ,'机舱MC' as lineName ");
            strBuffer.AppendLine(" ,OrderNum as orderNum ");
            strBuffer.AppendLine(" ,OrderType as orderType ");
            strBuffer.AppendLine(" ,CarType as carType ");
            strBuffer.AppendLine(" ,BECarType as wsCarType ");
            strBuffer.AppendLine(" ,BodySelCode as bodySelCode ");
            strBuffer.AppendLine(" ,BodyUse as bodyUse ");
            strBuffer.AppendLine(" ,SerialNumber as serialNumber ");
            strBuffer.AppendLine(" ,Line as line ");
            strBuffer.AppendLine(" from AVI_REPORT_MQ where ReportID = 'MC1002') t1 ");
            strBuffer.AppendLine(" Left JOIN ");
            strBuffer.AppendLine(" (select vin,'机舱MC下线' as ReportName,ReportTime as eTime from AVI_REPORT_MQ where ReportID = 'MC1360') t2 ");
            strBuffer.AppendLine(" ON ");
            strBuffer.AppendLine(" t1.vin=t2.vin ");
            strBuffer.AppendLine(" UNION ALL ");
            strBuffer.AppendLine(" select ");
            strBuffer.AppendLine(" t1.vin ");
            strBuffer.AppendLine(" ,t1.lineName ");
            strBuffer.AppendLine(" ,t1.ReportName as sReportName ");
            strBuffer.AppendLine(" ,t2.ReportName as eReportName ");
            strBuffer.AppendLine(" ,t1.sTime ");
            strBuffer.AppendLine(" ,t2.eTime ");
            strBuffer.AppendLine(" ,t1.LineType ");
            strBuffer.AppendLine(" ,t1.orderNum ");
            strBuffer.AppendLine(" ,t1.orderType ");
            strBuffer.AppendLine(" ,t1.carType ");
            strBuffer.AppendLine(" ,t1.wsCarType ");
            strBuffer.AppendLine(" ,t1.bodySelCode ");
            strBuffer.AppendLine(" ,t1.bodyUse ");
            strBuffer.AppendLine(" ,t1.serialNumber ");
            strBuffer.AppendLine(" ,t1.line ");
            strBuffer.AppendLine(" from ");
            strBuffer.AppendLine(" ( ");
            strBuffer.AppendLine(" select ");
            strBuffer.AppendLine(" vin ");
            strBuffer.AppendLine(" ,'前地板FF上线' as ReportName ");
            strBuffer.AppendLine(" ,ReportTime as sTime ");
            strBuffer.AppendLine(" , LineType ");
            strBuffer.AppendLine(" ,'前地板FF' as lineName ");
            strBuffer.AppendLine(" ,OrderNum as orderNum ");
            strBuffer.AppendLine(" ,OrderType as orderType ");
            strBuffer.AppendLine(" ,CarType as carType ");
            strBuffer.AppendLine(" ,BECarType as wsCarType ");
            strBuffer.AppendLine(" ,BodySelCode as bodySelCode ");
            strBuffer.AppendLine(" ,BodyUse as bodyUse ");
            strBuffer.AppendLine(" ,SerialNumber as serialNumber ");
            strBuffer.AppendLine(" ,Line as line ");
            strBuffer.AppendLine(" from AVI_REPORT_MQ where ReportID = 'FF1001') t1 ");
            strBuffer.AppendLine(" Left JOIN ");
            strBuffer.AppendLine(" (select vin,'前地板FF下线' as ReportName,ReportTime as eTime from AVI_REPORT_MQ where ReportID = 'FF1160') t2 ");
            strBuffer.AppendLine(" ON ");
            strBuffer.AppendLine(" t1.vin=t2.vin ");
            strBuffer.AppendLine(" UNION ALL ");
            strBuffer.AppendLine(" select ");
            strBuffer.AppendLine(" t1.vin ");
            strBuffer.AppendLine(" ,t1.lineName ");
            strBuffer.AppendLine(" ,t1.ReportName as sReportName ");
            strBuffer.AppendLine(" ,t2.ReportName as eReportName ");
            strBuffer.AppendLine(" ,t1.sTime ");
            strBuffer.AppendLine(" ,t2.eTime ");
            strBuffer.AppendLine(" ,t1.LineType ");
            strBuffer.AppendLine(" ,t1.orderNum ");
            strBuffer.AppendLine(" ,t1.orderType ");
            strBuffer.AppendLine(" ,t1.carType ");
            strBuffer.AppendLine(" ,t1.wsCarType ");
            strBuffer.AppendLine(" ,t1.bodySelCode ");
            strBuffer.AppendLine(" ,t1.bodyUse ");
            strBuffer.AppendLine(" ,t1.serialNumber ");
            strBuffer.AppendLine(" ,t1.line ");
            strBuffer.AppendLine(" from ");
            strBuffer.AppendLine(" ( ");
            strBuffer.AppendLine(" select ");
            strBuffer.AppendLine(" vin ");
            strBuffer.AppendLine(" ,'后地板RC上线' as ReportName ");
            strBuffer.AppendLine(" ,ReportTime as sTime ");
            strBuffer.AppendLine(" , LineType ");
            strBuffer.AppendLine(" ,'后地板RC' as lineName ");
            strBuffer.AppendLine(" ,OrderNum as orderNum ");
            strBuffer.AppendLine(" ,OrderType as orderType ");
            strBuffer.AppendLine(" ,CarType as carType ");
            strBuffer.AppendLine(" ,BECarType as wsCarType ");
            strBuffer.AppendLine(" ,BodySelCode as bodySelCode ");
            strBuffer.AppendLine(" ,BodyUse as bodyUse ");
            strBuffer.AppendLine(" ,SerialNumber as serialNumber ");
            strBuffer.AppendLine(" ,Line as line ");
            strBuffer.AppendLine(" from AVI_REPORT_MQ where ReportID = 'RC1010') t1 ");
            strBuffer.AppendLine(" Left JOIN ");
            strBuffer.AppendLine(" (select vin,'后地板RC下线' as ReportName,ReportTime as eTime from AVI_REPORT_MQ where ReportID = 'RC1320') t2 ");
            strBuffer.AppendLine(" ON ");
            strBuffer.AppendLine(" t1.vin=t2.vin ");
            strBuffer.AppendLine(" UNION ALL ");
            strBuffer.AppendLine(" select ");
            strBuffer.AppendLine(" t1.vin ");
            strBuffer.AppendLine(" ,t1.lineName ");
            strBuffer.AppendLine(" ,t1.ReportName as sReportName ");
            strBuffer.AppendLine(" ,t2.ReportName as eReportName ");
            strBuffer.AppendLine(" ,t1.sTime ");
            strBuffer.AppendLine(" ,t2.eTime ");
            strBuffer.AppendLine(" ,t1.LineType ");
            strBuffer.AppendLine(" ,t1.orderNum ");
            strBuffer.AppendLine(" ,t1.orderType ");
            strBuffer.AppendLine(" ,t1.carType ");
            strBuffer.AppendLine(" ,t1.wsCarType ");
            strBuffer.AppendLine(" ,t1.bodySelCode ");
            strBuffer.AppendLine(" ,t1.bodyUse ");
            strBuffer.AppendLine(" ,t1.serialNumber ");
            strBuffer.AppendLine(" ,t1.line ");
            strBuffer.AppendLine(" from ");
            strBuffer.AppendLine(" ( ");
            strBuffer.AppendLine(" select ");
            strBuffer.AppendLine(" vin ");
            strBuffer.AppendLine(" ,'左侧围内板SIL上线' as ReportName ");
            strBuffer.AppendLine(" ,ReportTime as sTime ");
            strBuffer.AppendLine(" , LineType ");
            strBuffer.AppendLine(" ,'左侧围内板SIL' as lineName ");
            strBuffer.AppendLine(" ,OrderNum as orderNum ");
            strBuffer.AppendLine(" ,OrderType as orderType ");
            strBuffer.AppendLine(" ,CarType as carType ");
            strBuffer.AppendLine(" ,BECarType as wsCarType ");
            strBuffer.AppendLine(" ,BodySelCode as bodySelCode ");
            strBuffer.AppendLine(" ,BodyUse as bodyUse ");
            strBuffer.AppendLine(" ,SerialNumber as serialNumber ");
            strBuffer.AppendLine(" ,Line as line ");
            strBuffer.AppendLine(" from AVI_REPORT_MQ where ReportID = 'SI010L') t1 ");
            strBuffer.AppendLine(" Left JOIN ");
            strBuffer.AppendLine(" (select vin,'左侧围内板SIL下线' as ReportName,ReportTime as eTime from AVI_REPORT_MQ where ReportID = 'SI050L') t2 ");
            strBuffer.AppendLine(" ON ");
            strBuffer.AppendLine(" t1.vin=t2.vin ");
            strBuffer.AppendLine(" UNION ALL ");
            strBuffer.AppendLine(" select ");
            strBuffer.AppendLine(" t1.vin ");
            strBuffer.AppendLine(" ,t1.lineName ");
            strBuffer.AppendLine(" ,t1.ReportName as sReportName ");
            strBuffer.AppendLine(" ,t2.ReportName as eReportName ");
            strBuffer.AppendLine(" ,t1.sTime ");
            strBuffer.AppendLine(" ,t2.eTime ");
            strBuffer.AppendLine(" ,t1.LineType ");
            strBuffer.AppendLine(" ,t1.orderNum ");
            strBuffer.AppendLine(" ,t1.orderType ");
            strBuffer.AppendLine(" ,t1.carType ");
            strBuffer.AppendLine(" ,t1.wsCarType ");
            strBuffer.AppendLine(" ,t1.bodySelCode ");
            strBuffer.AppendLine(" ,t1.bodyUse ");
            strBuffer.AppendLine(" ,t1.serialNumber ");
            strBuffer.AppendLine(" ,t1.line ");
            strBuffer.AppendLine(" from ");
            strBuffer.AppendLine(" ( ");
            strBuffer.AppendLine(" select ");
            strBuffer.AppendLine(" vin ");
            strBuffer.AppendLine(" ,'右侧围内板SIR上线' as ReportName ");
            strBuffer.AppendLine(" ,ReportTime as sTime ");
            strBuffer.AppendLine(" , LineType ");
            strBuffer.AppendLine(" ,'右侧围内板SIR' as lineName ");
            strBuffer.AppendLine(" ,OrderNum as orderNum ");
            strBuffer.AppendLine(" ,OrderType as orderType ");
            strBuffer.AppendLine(" ,CarType as carType ");
            strBuffer.AppendLine(" ,BECarType as wsCarType ");
            strBuffer.AppendLine(" ,BodySelCode as bodySelCode ");
            strBuffer.AppendLine(" ,BodyUse as bodyUse ");
            strBuffer.AppendLine(" ,SerialNumber as serialNumber ");
            strBuffer.AppendLine(" ,Line as line ");
            strBuffer.AppendLine(" from AVI_REPORT_MQ where ReportID = 'SI010R') t1 ");
            strBuffer.AppendLine(" Left JOIN ");
            strBuffer.AppendLine(" (select vin,'右侧围内板SIR下线' as ReportName,ReportTime as eTime from AVI_REPORT_MQ where ReportID = 'SI050R') t2 ");
            strBuffer.AppendLine(" ON ");
            strBuffer.AppendLine(" t1.vin=t2.vin ");
            strBuffer.AppendLine(" UNION ALL ");
            strBuffer.AppendLine(" select ");
            strBuffer.AppendLine(" t1.vin ");
            strBuffer.AppendLine(" ,t1.lineName ");
            strBuffer.AppendLine(" ,t1.ReportName as sReportName ");
            strBuffer.AppendLine(" ,t2.ReportName as eReportName ");
            strBuffer.AppendLine(" ,t1.sTime ");
            strBuffer.AppendLine(" ,t2.eTime ");
            strBuffer.AppendLine(" ,t1.LineType ");
            strBuffer.AppendLine(" ,t1.orderNum ");
            strBuffer.AppendLine(" ,t1.orderType ");
            strBuffer.AppendLine(" ,t1.carType ");
            strBuffer.AppendLine(" ,t1.wsCarType ");
            strBuffer.AppendLine(" ,t1.bodySelCode ");
            strBuffer.AppendLine(" ,t1.bodyUse ");
            strBuffer.AppendLine(" ,t1.serialNumber ");
            strBuffer.AppendLine(" ,t1.line ");
            strBuffer.AppendLine(" from ");
            strBuffer.AppendLine(" ( ");
            strBuffer.AppendLine(" select ");
            strBuffer.AppendLine(" vin ");
            strBuffer.AppendLine(" ,'左侧围外板SOL上线' as ReportName ");
            strBuffer.AppendLine(" ,ReportTime as sTime ");
            strBuffer.AppendLine(" , LineType ");
            strBuffer.AppendLine(" ,'左侧围外板SOL' as lineName ");
            strBuffer.AppendLine(" ,OrderNum as orderNum ");
            strBuffer.AppendLine(" ,OrderType as orderType ");
            strBuffer.AppendLine(" ,CarType as carType ");
            strBuffer.AppendLine(" ,BECarType as wsCarType ");
            strBuffer.AppendLine(" ,BodySelCode as bodySelCode ");
            strBuffer.AppendLine(" ,BodyUse as bodyUse ");
            strBuffer.AppendLine(" ,SerialNumber as serialNumber ");
            strBuffer.AppendLine(" ,Line as line ");
            strBuffer.AppendLine(" from AVI_REPORT_MQ where ReportID = 'SO010L') t1 ");
            strBuffer.AppendLine(" Left JOIN ");
            strBuffer.AppendLine(" (select vin,'左侧围外板SOL下线' as ReportName,ReportTime as eTime from AVI_REPORT_MQ where ReportID = 'SO050L') t2 ");
            strBuffer.AppendLine(" ON ");
            strBuffer.AppendLine(" t1.vin=t2.vin ");
            strBuffer.AppendLine(" UNION ALL ");
            strBuffer.AppendLine(" select ");
            strBuffer.AppendLine(" t1.vin ");
            strBuffer.AppendLine(" ,t1.lineName ");
            strBuffer.AppendLine(" ,t1.ReportName as sReportName ");
            strBuffer.AppendLine(" ,t2.ReportName as eReportName ");
            strBuffer.AppendLine(" ,t1.sTime ");
            strBuffer.AppendLine(" ,t2.eTime ");
            strBuffer.AppendLine(" ,t1.LineType ");
            strBuffer.AppendLine(" ,t1.orderNum ");
            strBuffer.AppendLine(" ,t1.orderType ");
            strBuffer.AppendLine(" ,t1.carType ");
            strBuffer.AppendLine(" ,t1.wsCarType ");
            strBuffer.AppendLine(" ,t1.bodySelCode ");
            strBuffer.AppendLine(" ,t1.bodyUse ");
            strBuffer.AppendLine(" ,t1.serialNumber ");
            strBuffer.AppendLine(" ,t1.line ");
            strBuffer.AppendLine(" from ");
            strBuffer.AppendLine(" ( ");
            strBuffer.AppendLine(" select ");
            strBuffer.AppendLine(" vin ");
            strBuffer.AppendLine(" ,'右侧围外板SOR上线' as ReportName ");
            strBuffer.AppendLine(" ,ReportTime as sTime ");
            strBuffer.AppendLine(" , LineType ");
            strBuffer.AppendLine(" ,'右侧围外板SOR' as lineName ");
            strBuffer.AppendLine(" ,OrderNum as orderNum ");
            strBuffer.AppendLine(" ,OrderType as orderType ");
            strBuffer.AppendLine(" ,CarType as carType ");
            strBuffer.AppendLine(" ,BECarType as wsCarType ");
            strBuffer.AppendLine(" ,BodySelCode as bodySelCode ");
            strBuffer.AppendLine(" ,BodyUse as bodyUse ");
            strBuffer.AppendLine(" ,SerialNumber as serialNumber ");
            strBuffer.AppendLine(" ,Line as line ");
            strBuffer.AppendLine(" from AVI_REPORT_MQ where ReportID = 'SO010R') t1 ");
            strBuffer.AppendLine(" Left JOIN ");
            strBuffer.AppendLine(" (select vin,'右侧围外板SOR下线' as ReportName,ReportTime as eTime from AVI_REPORT_MQ where ReportID = 'SO050R') t2 ");
            strBuffer.AppendLine(" ON ");
            strBuffer.AppendLine(" t1.vin=t2.vin ");
            strBuffer.AppendLine(" UNION ALL ");
            strBuffer.AppendLine(" select ");
            strBuffer.AppendLine(" t1.vin ");
            strBuffer.AppendLine(" ,t1.lineName ");
            strBuffer.AppendLine(" ,t1.ReportName as sReportName ");
            strBuffer.AppendLine(" ,t2.ReportName as eReportName ");
            strBuffer.AppendLine(" ,t1.sTime ");
            strBuffer.AppendLine(" ,t2.eTime ");
            strBuffer.AppendLine(" ,t1.LineType ");
            strBuffer.AppendLine(" ,t1.orderNum ");
            strBuffer.AppendLine(" ,t1.orderType ");
            strBuffer.AppendLine(" ,t1.carType ");
            strBuffer.AppendLine(" ,t1.wsCarType ");
            strBuffer.AppendLine(" ,t1.bodySelCode ");
            strBuffer.AppendLine(" ,t1.bodyUse ");
            strBuffer.AppendLine(" ,t1.serialNumber ");
            strBuffer.AppendLine(" ,t1.line ");
            strBuffer.AppendLine(" from ");
            strBuffer.AppendLine(" ( ");
            strBuffer.AppendLine(" select ");
            strBuffer.AppendLine(" vin ");
            strBuffer.AppendLine(" ,'左前门FDL上线' as ReportName ");
            strBuffer.AppendLine(" ,ReportTime as sTime ");
            strBuffer.AppendLine(" , LineType ");
            strBuffer.AppendLine(" ,'左前门FDL' as lineName ");
            strBuffer.AppendLine(" ,OrderNum as orderNum ");
            strBuffer.AppendLine(" ,OrderType as orderType ");
            strBuffer.AppendLine(" ,CarType as carType ");
            strBuffer.AppendLine(" ,BECarType as wsCarType ");
            strBuffer.AppendLine(" ,BodySelCode as bodySelCode ");
            strBuffer.AppendLine(" ,BodyUse as bodyUse ");
            strBuffer.AppendLine(" ,SerialNumber as serialNumber ");
            strBuffer.AppendLine(" ,Line as line ");
            strBuffer.AppendLine(" from AVI_REPORT_MQ where ReportID = 'FD1010') t1 ");
            strBuffer.AppendLine(" Left JOIN ");
            strBuffer.AppendLine(" (select vin,'左前门FDL下线' as ReportName,ReportTime as eTime from AVI_REPORT_MQ where ReportID = 'FD1330') t2 ");
            strBuffer.AppendLine(" ON ");
            strBuffer.AppendLine(" t1.vin=t2.vin ");
            strBuffer.AppendLine(" UNION ALL ");
            strBuffer.AppendLine(" select ");
            strBuffer.AppendLine(" t1.vin ");
            strBuffer.AppendLine(" ,t1.lineName ");
            strBuffer.AppendLine(" ,t1.ReportName as sReportName ");
            strBuffer.AppendLine(" ,t2.ReportName as eReportName ");
            strBuffer.AppendLine(" ,t1.sTime ");
            strBuffer.AppendLine(" ,t2.eTime ");
            strBuffer.AppendLine(" ,t1.LineType ");
            strBuffer.AppendLine(" ,t1.orderNum ");
            strBuffer.AppendLine(" ,t1.orderType ");
            strBuffer.AppendLine(" ,t1.carType ");
            strBuffer.AppendLine(" ,t1.wsCarType ");
            strBuffer.AppendLine(" ,t1.bodySelCode ");
            strBuffer.AppendLine(" ,t1.bodyUse ");
            strBuffer.AppendLine(" ,t1.serialNumber ");
            strBuffer.AppendLine(" ,t1.line ");
            strBuffer.AppendLine(" from ");
            strBuffer.AppendLine(" ( ");
            strBuffer.AppendLine(" select ");
            strBuffer.AppendLine(" vin ");
            strBuffer.AppendLine(" ,'右前门FDR上线' as ReportName ");
            strBuffer.AppendLine(" ,ReportTime as sTime ");
            strBuffer.AppendLine(" , LineType ");
            strBuffer.AppendLine(" ,'右前门FDR' as lineName ");
            strBuffer.AppendLine(" ,OrderNum as orderNum ");
            strBuffer.AppendLine(" ,OrderType as orderType ");
            strBuffer.AppendLine(" ,CarType as carType ");
            strBuffer.AppendLine(" ,BECarType as wsCarType ");
            strBuffer.AppendLine(" ,BodySelCode as bodySelCode ");
            strBuffer.AppendLine(" ,BodyUse as bodyUse ");
            strBuffer.AppendLine(" ,SerialNumber as serialNumber ");
            strBuffer.AppendLine(" ,Line as line ");
            strBuffer.AppendLine(" from AVI_REPORT_MQ where ReportID = 'FD1000') t1 ");
            strBuffer.AppendLine(" Left JOIN ");
            strBuffer.AppendLine(" (select vin,'右前门FDR下线' as ReportName,ReportTime as eTime from AVI_REPORT_MQ where ReportID = 'FD1320') t2 ");
            strBuffer.AppendLine(" ON ");
            strBuffer.AppendLine(" t1.vin=t2.vin ");
            strBuffer.AppendLine(" UNION ALL ");
            strBuffer.AppendLine(" select ");
            strBuffer.AppendLine(" t1.vin ");
            strBuffer.AppendLine(" ,t1.lineName ");
            strBuffer.AppendLine(" ,t1.ReportName as sReportName ");
            strBuffer.AppendLine(" ,t2.ReportName as eReportName ");
            strBuffer.AppendLine(" ,t1.sTime ");
            strBuffer.AppendLine(" ,t2.eTime ");
            strBuffer.AppendLine(" ,t1.LineType ");
            strBuffer.AppendLine(" ,t1.orderNum ");
            strBuffer.AppendLine(" ,t1.orderType ");
            strBuffer.AppendLine(" ,t1.carType ");
            strBuffer.AppendLine(" ,t1.wsCarType ");
            strBuffer.AppendLine(" ,t1.bodySelCode ");
            strBuffer.AppendLine(" ,t1.bodyUse ");
            strBuffer.AppendLine(" ,t1.serialNumber ");
            strBuffer.AppendLine(" ,t1.line ");
            strBuffer.AppendLine(" from ");
            strBuffer.AppendLine(" ( ");
            strBuffer.AppendLine(" select ");
            strBuffer.AppendLine(" vin ");
            strBuffer.AppendLine(" ,'左后门RDL上线' as ReportName ");
            strBuffer.AppendLine(" ,ReportTime as sTime ");
            strBuffer.AppendLine(" , LineType ");
            strBuffer.AppendLine(" ,'左后门RDL' as lineName ");
            strBuffer.AppendLine(" ,OrderNum as orderNum ");
            strBuffer.AppendLine(" ,OrderType as orderType ");
            strBuffer.AppendLine(" ,CarType as carType ");
            strBuffer.AppendLine(" ,BECarType as wsCarType ");
            strBuffer.AppendLine(" ,BodySelCode as bodySelCode ");
            strBuffer.AppendLine(" ,BodyUse as bodyUse ");
            strBuffer.AppendLine(" ,SerialNumber as serialNumber ");
            strBuffer.AppendLine(" ,Line as line ");
            strBuffer.AppendLine(" from AVI_REPORT_MQ where ReportID = 'RD1010') t1 ");
            strBuffer.AppendLine(" Left JOIN ");
            strBuffer.AppendLine(" (select vin,'左后门RDL下线' as ReportName,ReportTime as eTime from AVI_REPORT_MQ where ReportID = 'RD1330') t2 ");
            strBuffer.AppendLine(" ON ");
            strBuffer.AppendLine(" t1.vin=t2.vin ");
            strBuffer.AppendLine(" UNION ALL ");
            strBuffer.AppendLine(" select ");
            strBuffer.AppendLine(" t1.vin ");
            strBuffer.AppendLine(" ,t1.lineName ");
            strBuffer.AppendLine(" ,t1.ReportName as sReportName ");
            strBuffer.AppendLine(" ,t2.ReportName as eReportName ");
            strBuffer.AppendLine(" ,t1.sTime ");
            strBuffer.AppendLine(" ,t2.eTime ");
            strBuffer.AppendLine(" ,t1.LineType ");
            strBuffer.AppendLine(" ,t1.orderNum ");
            strBuffer.AppendLine(" ,t1.orderType ");
            strBuffer.AppendLine(" ,t1.carType ");
            strBuffer.AppendLine(" ,t1.wsCarType ");
            strBuffer.AppendLine(" ,t1.bodySelCode ");
            strBuffer.AppendLine(" ,t1.bodyUse ");
            strBuffer.AppendLine(" ,t1.serialNumber ");
            strBuffer.AppendLine(" ,t1.line ");
            strBuffer.AppendLine(" from ");
            strBuffer.AppendLine(" ( ");
            strBuffer.AppendLine(" select ");
            strBuffer.AppendLine(" vin ");
            strBuffer.AppendLine(" ,'右后门RDR上线' as ReportName ");
            strBuffer.AppendLine(" ,ReportTime as sTime ");
            strBuffer.AppendLine(" , LineType ");
            strBuffer.AppendLine(" ,'右后门RDR' as lineName ");
            strBuffer.AppendLine(" ,OrderNum as orderNum ");
            strBuffer.AppendLine(" ,OrderType as orderType ");
            strBuffer.AppendLine(" ,CarType as carType ");
            strBuffer.AppendLine(" ,BECarType as wsCarType ");
            strBuffer.AppendLine(" ,BodySelCode as bodySelCode ");
            strBuffer.AppendLine(" ,BodyUse as bodyUse ");
            strBuffer.AppendLine(" ,SerialNumber as serialNumber ");
            strBuffer.AppendLine(" ,Line as line ");
            strBuffer.AppendLine(" from AVI_REPORT_MQ where ReportID = 'RD1000') t1 ");
            strBuffer.AppendLine(" Left JOIN ");
            strBuffer.AppendLine(" (select vin,'右后门RDR下线' as ReportName,ReportTime as eTime from AVI_REPORT_MQ where ReportID = 'RD1320') t2 ");
            strBuffer.AppendLine(" ON ");
            strBuffer.AppendLine(" t1.vin=t2.vin ");
            strBuffer.AppendLine(" UNION ALL ");
            strBuffer.AppendLine(" select ");
            strBuffer.AppendLine(" t1.vin ");
            strBuffer.AppendLine(" ,t1.lineName ");
            strBuffer.AppendLine(" ,t1.ReportName as sReportName ");
            strBuffer.AppendLine(" ,t2.ReportName as eReportName ");
            strBuffer.AppendLine(" ,t1.sTime ");
            strBuffer.AppendLine(" ,t2.eTime ");
            strBuffer.AppendLine(" ,t1.LineType ");
            strBuffer.AppendLine(" ,t1.orderNum ");
            strBuffer.AppendLine(" ,t1.orderType ");
            strBuffer.AppendLine(" ,t1.carType ");
            strBuffer.AppendLine(" ,t1.wsCarType ");
            strBuffer.AppendLine(" ,t1.bodySelCode ");
            strBuffer.AppendLine(" ,t1.bodyUse ");
            strBuffer.AppendLine(" ,t1.serialNumber ");
            strBuffer.AppendLine(" ,t1.line ");
            strBuffer.AppendLine(" from ");
            strBuffer.AppendLine(" ( ");
            strBuffer.AppendLine(" select ");
            strBuffer.AppendLine(" vin ");
            strBuffer.AppendLine(" ,'顶盖RF上线' as ReportName ");
            strBuffer.AppendLine(" ,ReportTime as sTime ");
            strBuffer.AppendLine(" , LineType ");
            strBuffer.AppendLine(" ,'顶盖RF' as lineName ");
            strBuffer.AppendLine(" ,OrderNum as orderNum ");
            strBuffer.AppendLine(" ,OrderType as orderType ");
            strBuffer.AppendLine(" ,CarType as carType ");
            strBuffer.AppendLine(" ,BECarType as wsCarType ");
            strBuffer.AppendLine(" ,BodySelCode as bodySelCode ");
            strBuffer.AppendLine(" ,BodyUse as bodyUse ");
            strBuffer.AppendLine(" ,SerialNumber as serialNumber ");
            strBuffer.AppendLine(" ,Line as line ");
            strBuffer.AppendLine(" from AVI_REPORT_MQ where ReportID = 'RF1010') t1 ");
            strBuffer.AppendLine(" Left JOIN ");
            strBuffer.AppendLine(" (select vin,'顶盖RF下线' as ReportName,ReportTime as eTime from AVI_REPORT_MQ where ReportID = 'RF1070') t2 ");
            strBuffer.AppendLine(" ON ");
            strBuffer.AppendLine(" t1.vin=t2.vin ");
            strBuffer.AppendLine(" UNION ALL ");
            strBuffer.AppendLine(" select ");
            strBuffer.AppendLine(" t1.vin ");
            strBuffer.AppendLine(" ,t1.lineName ");
            strBuffer.AppendLine(" ,t1.ReportName as sReportName ");
            strBuffer.AppendLine(" ,t2.ReportName as eReportName ");
            strBuffer.AppendLine(" ,t1.sTime ");
            strBuffer.AppendLine(" ,t2.eTime ");
            strBuffer.AppendLine(" ,t1.LineType ");
            strBuffer.AppendLine(" ,t1.orderNum ");
            strBuffer.AppendLine(" ,t1.orderType ");
            strBuffer.AppendLine(" ,t1.carType ");
            strBuffer.AppendLine(" ,t1.wsCarType ");
            strBuffer.AppendLine(" ,t1.bodySelCode ");
            strBuffer.AppendLine(" ,t1.bodyUse ");
            strBuffer.AppendLine(" ,t1.serialNumber ");
            strBuffer.AppendLine(" ,t1.line ");
            strBuffer.AppendLine(" from ");
            strBuffer.AppendLine(" ( ");
            strBuffer.AppendLine(" select ");
            strBuffer.AppendLine(" vin ");
            strBuffer.AppendLine(" ,'前盖HD上线' as ReportName ");
            strBuffer.AppendLine(" ,ReportTime as sTime ");
            strBuffer.AppendLine(" , LineType ");
            strBuffer.AppendLine(" ,'前盖HD' as lineName ");
            strBuffer.AppendLine(" ,OrderNum as orderNum ");
            strBuffer.AppendLine(" ,OrderType as orderType ");
            strBuffer.AppendLine(" ,CarType as carType ");
            strBuffer.AppendLine(" ,BECarType as wsCarType ");
            strBuffer.AppendLine(" ,BodySelCode as bodySelCode ");
            strBuffer.AppendLine(" ,BodyUse as bodyUse ");
            strBuffer.AppendLine(" ,SerialNumber as serialNumber ");
            strBuffer.AppendLine(" ,Line as line ");
            strBuffer.AppendLine(" from AVI_REPORT_MQ where ReportID = 'HD1010') t1 ");
            strBuffer.AppendLine(" Left JOIN ");
            strBuffer.AppendLine(" (select vin,'前盖HD下线' as ReportName,ReportTime as eTime from AVI_REPORT_MQ where ReportID = 'HD1100') t2 ");
            strBuffer.AppendLine(" ON ");
            strBuffer.AppendLine(" t1.vin=t2.vin ");
            strBuffer.AppendLine(" UNION ALL ");
            strBuffer.AppendLine(" select ");
            strBuffer.AppendLine(" t1.vin ");
            strBuffer.AppendLine(" ,t1.lineName ");
            strBuffer.AppendLine(" ,t1.ReportName as sReportName ");
            strBuffer.AppendLine(" ,t2.ReportName as eReportName ");
            strBuffer.AppendLine(" ,t1.sTime ");
            strBuffer.AppendLine(" ,t2.eTime ");
            strBuffer.AppendLine(" ,t1.LineType ");
            strBuffer.AppendLine(" ,t1.orderNum ");
            strBuffer.AppendLine(" ,t1.orderType ");
            strBuffer.AppendLine(" ,t1.carType ");
            strBuffer.AppendLine(" ,t1.wsCarType ");
            strBuffer.AppendLine(" ,t1.bodySelCode ");
            strBuffer.AppendLine(" ,t1.bodyUse ");
            strBuffer.AppendLine(" ,t1.serialNumber ");
            strBuffer.AppendLine(" ,t1.line ");
            strBuffer.AppendLine(" from ");
            strBuffer.AppendLine(" ( ");
            strBuffer.AppendLine(" select ");
            strBuffer.AppendLine(" vin ");
            strBuffer.AppendLine(" ,'后举门DL上线' as ReportName ");
            strBuffer.AppendLine(" ,ReportTime as sTime ");
            strBuffer.AppendLine(" , LineType ");
            strBuffer.AppendLine(" ,'后举门DL' as lineName ");
            strBuffer.AppendLine(" ,OrderNum as orderNum ");
            strBuffer.AppendLine(" ,OrderType as orderType ");
            strBuffer.AppendLine(" ,CarType as carType ");
            strBuffer.AppendLine(" ,BECarType as wsCarType ");
            strBuffer.AppendLine(" ,BodySelCode as bodySelCode ");
            strBuffer.AppendLine(" ,BodyUse as bodyUse ");
            strBuffer.AppendLine(" ,SerialNumber as serialNumber ");
            strBuffer.AppendLine(" ,Line as line ");
            strBuffer.AppendLine(" from AVI_REPORT_MQ where ReportID = 'DL1010') t1 ");
            strBuffer.AppendLine(" Left JOIN ");
            strBuffer.AppendLine(" (select vin,'后举门DL下线' as ReportName,ReportTime as eTime from AVI_REPORT_MQ where ReportID = 'DL1210') t2 ");
            strBuffer.AppendLine(" ON ");
            strBuffer.AppendLine(" t1.vin=t2.vin ");
            strBuffer.AppendLine(" UNION ALL ");
            strBuffer.AppendLine(" select ");
            strBuffer.AppendLine(" t1.vin ");
            strBuffer.AppendLine(" ,t1.lineName ");
            strBuffer.AppendLine(" ,t1.ReportName as sReportName ");
            strBuffer.AppendLine(" ,t2.ReportName as eReportName ");
            strBuffer.AppendLine(" ,t1.sTime ");
            strBuffer.AppendLine(" ,t2.eTime ");
            strBuffer.AppendLine(" ,t1.LineType ");
            strBuffer.AppendLine(" ,t1.orderNum ");
            strBuffer.AppendLine(" ,t1.orderType ");
            strBuffer.AppendLine(" ,t1.carType ");
            strBuffer.AppendLine(" ,t1.wsCarType ");
            strBuffer.AppendLine(" ,t1.bodySelCode ");
            strBuffer.AppendLine(" ,t1.bodyUse ");
            strBuffer.AppendLine(" ,t1.serialNumber ");
            strBuffer.AppendLine(" ,t1.line ");
            strBuffer.AppendLine(" from ");
            strBuffer.AppendLine(" ( ");
            strBuffer.AppendLine(" select ");
            strBuffer.AppendLine(" vin ");
            strBuffer.AppendLine(" ,'地板UB上线' as ReportName ");
            strBuffer.AppendLine(" ,ReportTime as sTime ");
            strBuffer.AppendLine(" , LineType ");
            strBuffer.AppendLine(" ,'地板UB' as lineName ");
            strBuffer.AppendLine(" ,OrderNum as orderNum ");
            strBuffer.AppendLine(" ,OrderType as orderType ");
            strBuffer.AppendLine(" ,CarType as carType ");
            strBuffer.AppendLine(" ,BECarType as wsCarType ");
            strBuffer.AppendLine(" ,BodySelCode as bodySelCode ");
            strBuffer.AppendLine(" ,BodyUse as bodyUse ");
            strBuffer.AppendLine(" ,SerialNumber as serialNumber ");
            strBuffer.AppendLine(" ,Line as line ");
            strBuffer.AppendLine(" from AVI_REPORT_MQ where ReportID = 'UB1020') t1 ");
            strBuffer.AppendLine(" Left JOIN ");
            strBuffer.AppendLine(" (select vin,'地板UB下线' as ReportName,ReportTime as eTime from AVI_REPORT_MQ where ReportID = 'UB1080') t2 ");
            strBuffer.AppendLine(" ON ");
            strBuffer.AppendLine(" t1.vin=t2.vin ");
            strBuffer.AppendLine(" UNION ALL ");
            strBuffer.AppendLine(" select ");
            strBuffer.AppendLine(" t1.vin ");
            strBuffer.AppendLine(" ,t1.lineName ");
            strBuffer.AppendLine(" ,t1.ReportName as sReportName ");
            strBuffer.AppendLine(" ,t2.ReportName as eReportName ");
            strBuffer.AppendLine(" ,t1.sTime ");
            strBuffer.AppendLine(" ,t2.eTime ");
            strBuffer.AppendLine(" ,t1.LineType ");
            strBuffer.AppendLine(" ,t1.orderNum ");
            strBuffer.AppendLine(" ,t1.orderType ");
            strBuffer.AppendLine(" ,t1.carType ");
            strBuffer.AppendLine(" ,t1.wsCarType ");
            strBuffer.AppendLine(" ,t1.bodySelCode ");
            strBuffer.AppendLine(" ,t1.bodyUse ");
            strBuffer.AppendLine(" ,t1.serialNumber ");
            strBuffer.AppendLine(" ,t1.line ");
            strBuffer.AppendLine(" from ");
            strBuffer.AppendLine(" ( ");
            strBuffer.AppendLine(" select ");
            strBuffer.AppendLine(" vin ");
            strBuffer.AppendLine(" ,'下车体补焊一UR1上线' as ReportName ");
            strBuffer.AppendLine(" ,ReportTime as sTime ");
            strBuffer.AppendLine(" , LineType ");
            strBuffer.AppendLine(" ,'下车体补焊一UR1' as lineName ");
            strBuffer.AppendLine(" ,OrderNum as orderNum ");
            strBuffer.AppendLine(" ,OrderType as orderType ");
            strBuffer.AppendLine(" ,CarType as carType ");
            strBuffer.AppendLine(" ,BECarType as wsCarType ");
            strBuffer.AppendLine(" ,BodySelCode as bodySelCode ");
            strBuffer.AppendLine(" ,BodyUse as bodyUse ");
            strBuffer.AppendLine(" ,SerialNumber as serialNumber ");
            strBuffer.AppendLine(" ,Line as line ");
            strBuffer.AppendLine(" from AVI_REPORT_MQ where ReportID = 'UR1090') t1 ");
            strBuffer.AppendLine(" Left JOIN ");
            strBuffer.AppendLine(" (select vin,'下车体补焊一UR1下线' as ReportName,ReportTime as eTime from AVI_REPORT_MQ where ReportID = 'UR1180') t2 ");
            strBuffer.AppendLine(" ON ");
            strBuffer.AppendLine(" t1.vin=t2.vin ");
            strBuffer.AppendLine(" UNION ALL ");
            strBuffer.AppendLine(" select ");
            strBuffer.AppendLine(" t1.vin ");
            strBuffer.AppendLine(" ,t1.lineName ");
            strBuffer.AppendLine(" ,t1.ReportName as sReportName ");
            strBuffer.AppendLine(" ,t2.ReportName as eReportName ");
            strBuffer.AppendLine(" ,t1.sTime ");
            strBuffer.AppendLine(" ,t2.eTime ");
            strBuffer.AppendLine(" ,t1.LineType ");
            strBuffer.AppendLine(" ,t1.orderNum ");
            strBuffer.AppendLine(" ,t1.orderType ");
            strBuffer.AppendLine(" ,t1.carType ");
            strBuffer.AppendLine(" ,t1.wsCarType ");
            strBuffer.AppendLine(" ,t1.bodySelCode ");
            strBuffer.AppendLine(" ,t1.bodyUse ");
            strBuffer.AppendLine(" ,t1.serialNumber ");
            strBuffer.AppendLine(" ,t1.line ");
            strBuffer.AppendLine(" from ");
            strBuffer.AppendLine(" ( ");
            strBuffer.AppendLine(" select ");
            strBuffer.AppendLine(" vin ");
            strBuffer.AppendLine(" ,'下车体补焊二UR2上线' as ReportName ");
            strBuffer.AppendLine(" ,ReportTime as sTime ");
            strBuffer.AppendLine(" , LineType ");
            strBuffer.AppendLine(" ,'下车体补焊二UR2' as lineName ");
            strBuffer.AppendLine(" ,OrderNum as orderNum ");
            strBuffer.AppendLine(" ,OrderType as orderType ");
            strBuffer.AppendLine(" ,CarType as carType ");
            strBuffer.AppendLine(" ,BECarType as wsCarType ");
            strBuffer.AppendLine(" ,BodySelCode as bodySelCode ");
            strBuffer.AppendLine(" ,BodyUse as bodyUse ");
            strBuffer.AppendLine(" ,SerialNumber as serialNumber ");
            strBuffer.AppendLine(" ,Line as line ");
            strBuffer.AppendLine(" from AVI_REPORT_MQ where ReportID = 'UR1190') t1 ");
            strBuffer.AppendLine(" Left JOIN ");
            strBuffer.AppendLine(" (select vin,'下车体补焊二UR2下线' as ReportName,ReportTime as eTime from AVI_REPORT_MQ where ReportID = 'UR1270') t2 ");
            strBuffer.AppendLine(" ON ");
            strBuffer.AppendLine(" t1.vin=t2.vin ");
            strBuffer.AppendLine(" UNION ALL ");
            strBuffer.AppendLine(" select ");
            strBuffer.AppendLine(" t1.vin ");
            strBuffer.AppendLine(" ,t1.lineName ");
            strBuffer.AppendLine(" ,t1.ReportName as sReportName ");
            strBuffer.AppendLine(" ,t2.ReportName as eReportName ");
            strBuffer.AppendLine(" ,t1.sTime ");
            strBuffer.AppendLine(" ,t2.eTime ");
            strBuffer.AppendLine(" ,t1.LineType ");
            strBuffer.AppendLine(" ,t1.orderNum ");
            strBuffer.AppendLine(" ,t1.orderType ");
            strBuffer.AppendLine(" ,t1.carType ");
            strBuffer.AppendLine(" ,t1.wsCarType ");
            strBuffer.AppendLine(" ,t1.bodySelCode ");
            strBuffer.AppendLine(" ,t1.bodyUse ");
            strBuffer.AppendLine(" ,t1.serialNumber ");
            strBuffer.AppendLine(" ,t1.line ");
            strBuffer.AppendLine(" from ");
            strBuffer.AppendLine(" ( ");
            strBuffer.AppendLine(" select ");
            strBuffer.AppendLine(" vin ");
            strBuffer.AppendLine(" ,'内总拼FI上线' as ReportName ");
            strBuffer.AppendLine(" ,ReportTime as sTime ");
            strBuffer.AppendLine(" , LineType ");
            strBuffer.AppendLine(" ,'内总拼FI' as lineName ");
            strBuffer.AppendLine(" ,OrderNum as orderNum ");
            strBuffer.AppendLine(" ,OrderType as orderType ");
            strBuffer.AppendLine(" ,CarType as carType ");
            strBuffer.AppendLine(" ,BECarType as wsCarType ");
            strBuffer.AppendLine(" ,BodySelCode as bodySelCode ");
            strBuffer.AppendLine(" ,BodyUse as bodyUse ");
            strBuffer.AppendLine(" ,SerialNumber as serialNumber ");
            strBuffer.AppendLine(" ,Line as line ");
            strBuffer.AppendLine(" from AVI_REPORT_MQ where ReportID = 'FI1000') t1 ");
            strBuffer.AppendLine(" Left JOIN ");
            strBuffer.AppendLine(" (select vin,'内总拼FI下线' as ReportName,ReportTime as eTime from AVI_REPORT_MQ where ReportID = 'FI1100') t2 ");
            strBuffer.AppendLine(" ON ");
            strBuffer.AppendLine(" t1.vin=t2.vin ");
            strBuffer.AppendLine(" UNION ALL ");
            strBuffer.AppendLine(" select ");
            strBuffer.AppendLine(" t1.vin ");
            strBuffer.AppendLine(" ,t1.lineName ");
            strBuffer.AppendLine(" ,t1.ReportName as sReportName ");
            strBuffer.AppendLine(" ,t2.ReportName as eReportName ");
            strBuffer.AppendLine(" ,t1.sTime ");
            strBuffer.AppendLine(" ,t2.eTime ");
            strBuffer.AppendLine(" ,t1.LineType ");
            strBuffer.AppendLine(" ,t1.orderNum ");
            strBuffer.AppendLine(" ,t1.orderType ");
            strBuffer.AppendLine(" ,t1.carType ");
            strBuffer.AppendLine(" ,t1.wsCarType ");
            strBuffer.AppendLine(" ,t1.bodySelCode ");
            strBuffer.AppendLine(" ,t1.bodyUse ");
            strBuffer.AppendLine(" ,t1.serialNumber ");
            strBuffer.AppendLine(" ,t1.line ");
            strBuffer.AppendLine(" from ");
            strBuffer.AppendLine(" ( ");
            strBuffer.AppendLine(" select ");
            strBuffer.AppendLine(" vin ");
            strBuffer.AppendLine(" ,'补焊二RL2上线' as ReportName ");
            strBuffer.AppendLine(" ,ReportTime as sTime ");
            strBuffer.AppendLine(" , LineType ");
            strBuffer.AppendLine(" ,'补焊二RL2' as lineName ");
            strBuffer.AppendLine(" ,OrderNum as orderNum ");
            strBuffer.AppendLine(" ,OrderType as orderType ");
            strBuffer.AppendLine(" ,CarType as carType ");
            strBuffer.AppendLine(" ,BECarType as wsCarType ");
            strBuffer.AppendLine(" ,BodySelCode as bodySelCode ");
            strBuffer.AppendLine(" ,BodyUse as bodyUse ");
            strBuffer.AppendLine(" ,SerialNumber as serialNumber ");
            strBuffer.AppendLine(" ,Line as line ");
            strBuffer.AppendLine(" from AVI_REPORT_MQ where ReportID = 'RL2000') t1 ");
            strBuffer.AppendLine(" Left JOIN ");
            strBuffer.AppendLine(" (select vin,'补焊二RL2下线' as ReportName,ReportTime as eTime from AVI_REPORT_MQ where ReportID = 'RL2100') t2 ");
            strBuffer.AppendLine(" ON ");
            strBuffer.AppendLine(" t1.vin=t2.vin ");
            strBuffer.AppendLine(" UNION ALL ");
            strBuffer.AppendLine(" select ");
            strBuffer.AppendLine(" t1.vin ");
            strBuffer.AppendLine(" ,t1.lineName ");
            strBuffer.AppendLine(" ,t1.ReportName as sReportName ");
            strBuffer.AppendLine(" ,t2.ReportName as eReportName ");
            strBuffer.AppendLine(" ,t1.sTime ");
            strBuffer.AppendLine(" ,t2.eTime ");
            strBuffer.AppendLine(" ,t1.LineType ");
            strBuffer.AppendLine(" ,t1.orderNum ");
            strBuffer.AppendLine(" ,t1.orderType ");
            strBuffer.AppendLine(" ,t1.carType ");
            strBuffer.AppendLine(" ,t1.wsCarType ");
            strBuffer.AppendLine(" ,t1.bodySelCode ");
            strBuffer.AppendLine(" ,t1.bodyUse ");
            strBuffer.AppendLine(" ,t1.serialNumber ");
            strBuffer.AppendLine(" ,t1.line ");
            strBuffer.AppendLine(" from ");
            strBuffer.AppendLine(" ( ");
            strBuffer.AppendLine(" select ");
            strBuffer.AppendLine(" vin ");
            strBuffer.AppendLine(" ,'外总拼FO上线' as ReportName ");
            strBuffer.AppendLine(" ,ReportTime as sTime ");
            strBuffer.AppendLine(" , LineType ");
            strBuffer.AppendLine(" ,'外总拼FO' as lineName ");
            strBuffer.AppendLine(" ,OrderNum as orderNum ");
            strBuffer.AppendLine(" ,OrderType as orderType ");
            strBuffer.AppendLine(" ,CarType as carType ");
            strBuffer.AppendLine(" ,BECarType as wsCarType ");
            strBuffer.AppendLine(" ,BodySelCode as bodySelCode ");
            strBuffer.AppendLine(" ,BodyUse as bodyUse ");
            strBuffer.AppendLine(" ,SerialNumber as serialNumber ");
            strBuffer.AppendLine(" ,Line as line ");
            strBuffer.AppendLine(" from AVI_REPORT_MQ where ReportID = 'FO3000') t1 ");
            strBuffer.AppendLine(" Left JOIN ");
            strBuffer.AppendLine(" (select vin,'外总拼FO下线' as ReportName,ReportTime as eTime from AVI_REPORT_MQ where ReportID = 'FO3100') t2 ");
            strBuffer.AppendLine(" ON ");
            strBuffer.AppendLine(" t1.vin=t2.vin ");
            strBuffer.AppendLine(" UNION ALL ");
            strBuffer.AppendLine(" select ");
            strBuffer.AppendLine(" t1.vin ");
            strBuffer.AppendLine(" ,t1.lineName ");
            strBuffer.AppendLine(" ,t1.ReportName as sReportName ");
            strBuffer.AppendLine(" ,t2.ReportName as eReportName ");
            strBuffer.AppendLine(" ,t1.sTime ");
            strBuffer.AppendLine(" ,t2.eTime ");
            strBuffer.AppendLine(" ,t1.LineType ");
            strBuffer.AppendLine(" ,t1.orderNum ");
            strBuffer.AppendLine(" ,t1.orderType ");
            strBuffer.AppendLine(" ,t1.carType ");
            strBuffer.AppendLine(" ,t1.wsCarType ");
            strBuffer.AppendLine(" ,t1.bodySelCode ");
            strBuffer.AppendLine(" ,t1.bodyUse ");
            strBuffer.AppendLine(" ,t1.serialNumber ");
            strBuffer.AppendLine(" ,t1.line ");
            strBuffer.AppendLine(" from ");
            strBuffer.AppendLine(" ( ");
            strBuffer.AppendLine(" select ");
            strBuffer.AppendLine(" vin ");
            strBuffer.AppendLine(" ,'补焊四RL4上线' as ReportName ");
            strBuffer.AppendLine(" ,ReportTime as sTime ");
            strBuffer.AppendLine(" , LineType ");
            strBuffer.AppendLine(" ,'补焊四RL4' as lineName ");
            strBuffer.AppendLine(" ,OrderNum as orderNum ");
            strBuffer.AppendLine(" ,OrderType as orderType ");
            strBuffer.AppendLine(" ,CarType as carType ");
            strBuffer.AppendLine(" ,BECarType as wsCarType ");
            strBuffer.AppendLine(" ,BodySelCode as bodySelCode ");
            strBuffer.AppendLine(" ,BodyUse as bodyUse ");
            strBuffer.AppendLine(" ,SerialNumber as serialNumber ");
            strBuffer.AppendLine(" ,Line as line ");
            strBuffer.AppendLine(" from AVI_REPORT_MQ where ReportID = 'RL4000') t1 ");
            strBuffer.AppendLine(" Left JOIN ");
            strBuffer.AppendLine(" (select vin,'补焊四RL4下线' as ReportName,ReportTime as eTime from AVI_REPORT_MQ where ReportID = 'RL4100') t2 ");
            strBuffer.AppendLine(" ON ");
            strBuffer.AppendLine(" t1.vin=t2.vin ");
            strBuffer.AppendLine(" UNION ALL ");
            strBuffer.AppendLine(" select ");
            strBuffer.AppendLine(" t1.vin ");
            strBuffer.AppendLine(" ,t1.lineName ");
            strBuffer.AppendLine(" ,t1.ReportName as sReportName ");
            strBuffer.AppendLine(" ,t2.ReportName as eReportName ");
            strBuffer.AppendLine(" ,t1.sTime ");
            strBuffer.AppendLine(" ,t2.eTime ");
            strBuffer.AppendLine(" ,t1.LineType ");
            strBuffer.AppendLine(" ,t1.orderNum ");
            strBuffer.AppendLine(" ,t1.orderType ");
            strBuffer.AppendLine(" ,t1.carType ");
            strBuffer.AppendLine(" ,t1.wsCarType ");
            strBuffer.AppendLine(" ,t1.bodySelCode ");
            strBuffer.AppendLine(" ,t1.bodyUse ");
            strBuffer.AppendLine(" ,t1.serialNumber ");
            strBuffer.AppendLine(" ,t1.line ");
            strBuffer.AppendLine(" from ");
            strBuffer.AppendLine(" ( ");
            strBuffer.AppendLine(" select ");
            strBuffer.AppendLine(" vin ");
            strBuffer.AppendLine(" ,'补焊五RL5上线' as ReportName ");
            strBuffer.AppendLine(" ,ReportTime as sTime ");
            strBuffer.AppendLine(" , LineType ");
            strBuffer.AppendLine(" ,'补焊五RL5' as lineName ");
            strBuffer.AppendLine(" ,OrderNum as orderNum ");
            strBuffer.AppendLine(" ,OrderType as orderType ");
            strBuffer.AppendLine(" ,CarType as carType ");
            strBuffer.AppendLine(" ,BECarType as wsCarType ");
            strBuffer.AppendLine(" ,BodySelCode as bodySelCode ");
            strBuffer.AppendLine(" ,BodyUse as bodyUse ");
            strBuffer.AppendLine(" ,SerialNumber as serialNumber ");
            strBuffer.AppendLine(" ,Line as line ");
            strBuffer.AppendLine(" from AVI_REPORT_MQ where ReportID = 'RL5000') t1 ");
            strBuffer.AppendLine(" Left JOIN ");
            strBuffer.AppendLine(" (select vin,'补焊五RL5下线' as ReportName,ReportTime as eTime from AVI_REPORT_MQ where ReportID = 'RL5090') t2 ");
            strBuffer.AppendLine(" ON ");
            strBuffer.AppendLine(" t1.vin=t2.vin ");
            strBuffer.AppendLine(" UNION ALL ");
            strBuffer.AppendLine(" select ");
            strBuffer.AppendLine(" t1.vin ");
            strBuffer.AppendLine(" ,t1.lineName ");
            strBuffer.AppendLine(" ,t1.ReportName as sReportName ");
            strBuffer.AppendLine(" ,t2.ReportName as eReportName ");
            strBuffer.AppendLine(" ,t1.sTime ");
            strBuffer.AppendLine(" ,t2.eTime ");
            strBuffer.AppendLine(" ,t1.LineType ");
            strBuffer.AppendLine(" ,t1.orderNum ");
            strBuffer.AppendLine(" ,t1.orderType ");
            strBuffer.AppendLine(" ,t1.carType ");
            strBuffer.AppendLine(" ,t1.wsCarType ");
            strBuffer.AppendLine(" ,t1.bodySelCode ");
            strBuffer.AppendLine(" ,t1.bodyUse ");
            strBuffer.AppendLine(" ,t1.serialNumber ");
            strBuffer.AppendLine(" ,t1.line ");
            strBuffer.AppendLine(" from ");
            strBuffer.AppendLine(" ( ");
            strBuffer.AppendLine(" select ");
            strBuffer.AppendLine(" vin ");
            strBuffer.AppendLine(" ,'补焊六RL6上线' as ReportName ");
            strBuffer.AppendLine(" ,ReportTime as sTime ");
            strBuffer.AppendLine(" , LineType ");
            strBuffer.AppendLine(" ,'补焊六RL6' as lineName ");
            strBuffer.AppendLine(" ,OrderNum as orderNum ");
            strBuffer.AppendLine(" ,OrderType as orderType ");
            strBuffer.AppendLine(" ,CarType as carType ");
            strBuffer.AppendLine(" ,BECarType as wsCarType ");
            strBuffer.AppendLine(" ,BodySelCode as bodySelCode ");
            strBuffer.AppendLine(" ,BodyUse as bodyUse ");
            strBuffer.AppendLine(" ,SerialNumber as serialNumber ");
            strBuffer.AppendLine(" ,Line as line ");
            strBuffer.AppendLine(" from AVI_REPORT_MQ where ReportID = 'RL6000') t1 ");
            strBuffer.AppendLine(" Left JOIN ");
            strBuffer.AppendLine(" (select vin,'补焊六RL6下线' as ReportName,ReportTime as eTime from AVI_REPORT_MQ where ReportID = 'RL6100') t2 ");
            strBuffer.AppendLine(" ON ");
            strBuffer.AppendLine(" t1.vin=t2.vin ");
            strBuffer.AppendLine(" UNION ALL ");
            strBuffer.AppendLine(" select ");
            strBuffer.AppendLine(" t1.vin ");
            strBuffer.AppendLine(" ,t1.lineName ");
            strBuffer.AppendLine(" ,t1.ReportName as sReportName ");
            strBuffer.AppendLine(" ,t2.ReportName as eReportName ");
            strBuffer.AppendLine(" ,t1.sTime ");
            strBuffer.AppendLine(" ,t2.eTime ");
            strBuffer.AppendLine(" ,t1.LineType ");
            strBuffer.AppendLine(" ,t1.orderNum ");
            strBuffer.AppendLine(" ,t1.orderType ");
            strBuffer.AppendLine(" ,t1.carType ");
            strBuffer.AppendLine(" ,t1.wsCarType ");
            strBuffer.AppendLine(" ,t1.bodySelCode ");
            strBuffer.AppendLine(" ,t1.bodyUse ");
            strBuffer.AppendLine(" ,t1.serialNumber ");
            strBuffer.AppendLine(" ,t1.line ");
            strBuffer.AppendLine(" from ");
            strBuffer.AppendLine(" ( ");
            strBuffer.AppendLine(" select ");
            strBuffer.AppendLine(" vin ");
            strBuffer.AppendLine(" ,'装配线MF1上线' as ReportName ");
            strBuffer.AppendLine(" ,ReportTime as sTime ");
            strBuffer.AppendLine(" , LineType ");
            strBuffer.AppendLine(" ,'装配线MF1' as lineName ");
            strBuffer.AppendLine(" ,OrderNum as orderNum ");
            strBuffer.AppendLine(" ,OrderType as orderType ");
            strBuffer.AppendLine(" ,CarType as carType ");
            strBuffer.AppendLine(" ,BECarType as wsCarType ");
            strBuffer.AppendLine(" ,BodySelCode as bodySelCode ");
            strBuffer.AppendLine(" ,BodyUse as bodyUse ");
            strBuffer.AppendLine(" ,SerialNumber as serialNumber ");
            strBuffer.AppendLine(" ,Line as line ");
            strBuffer.AppendLine(" from AVI_REPORT_MQ where ReportID = 'MF1000') t1 ");
            strBuffer.AppendLine(" Left JOIN ");
            strBuffer.AppendLine(" (select vin,'装配线MF1下线' as ReportName,ReportTime as eTime from AVI_REPORT_MQ where ReportID = 'MF1120') t2 ");
            strBuffer.AppendLine(" ON ");
            strBuffer.AppendLine(" t1.vin=t2.vin ");
            strBuffer.AppendLine(" ) t ");
            strBuffer.AppendLine(" where ");
            strBuffer.AppendLine(" 1=1 ");

            return strBuffer.ToString();
        }
    }
}

